"use client";

import { useState } from "react";
import { Briefcase, Target, Users, TrendingUp, Download, RefreshCw, FileText, CheckCircle } from "lucide-react";

interface BusinessPlanData {
  companyName: string;
  industry: string;
  mission: string;
  targetMarket: string;
  revenueModel: string;
  teamSize: string;
  funding: string;
  goals: string[];
}

export default function BusinessPlanGenerator() {
  const [data, setData] = useState<BusinessPlanData>({
    companyName: "",
    industry: "Technology",
    mission: "",
    targetMarket: "",
    revenueModel: "",
    teamSize: "1-10",
    funding: "Bootstrapped",
    goals: [""]
  });

  const [generatedPlan, setGeneratedPlan] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const industries = [
    "Technology", "Healthcare", "E-commerce", "Finance", "Education",
    "Food & Beverage", "Real Estate", "Manufacturing", "Services", "Media"
  ];

  const revenueModels = [
    "Subscription", "One-time Sale", "Freemium", "Marketplace Commission",
    "Advertising", "Licensing", "Consulting", "SaaS"
  ];

  const updateField = (field: keyof BusinessPlanData, value: string) => {
    setData({ ...data, [field]: value });
  };

  const updateGoal = (index: number, value: string) => {
    const newGoals = [...data.goals];
    newGoals[index] = value;
    setData({ ...data, goals: newGoals });
  };

  const addGoal = () => {
    setData({ ...data, goals: [...data.goals, ""] });
  };

  const removeGoal = (index: number) => {
    const newGoals = data.goals.filter((_, i) => i !== index);
    setData({ ...data, goals: newGoals });
  };

  const generatePlan = async () => {
    if (!data.companyName || !data.mission) return;

    setIsGenerating(true);

    setTimeout(() => {
      const plan = `
# ${data.companyName} - Business Plan

## 1. EXECUTIVE SUMMARY
${data.companyName} is a ${data.industry} company dedicated to ${data.mission}. 
We target ${data.targetMarket} and aim to revolutionize the industry through innovation.

## 2. COMPANY OVERVIEW
- **Company Name:** ${data.companyName}
- **Industry:** ${data.industry}
- **Mission Statement:** ${data.mission}
- **Team Size:** ${data.teamSize} employees
- **Funding Status:** ${data.funding}

## 3. TARGET MARKET
${data.targetMarket}

### Market Size
- Total Addressable Market (TAM): ₹100Cr+
- Serviceable Addressable Market (SAM): ₹10Cr+
- Serviceable Obtainable Market (SOM): ₹1Cr+

## 4. PRODUCTS & SERVICES
Our core offerings include:
- Primary Product/Service 1
- Primary Product/Service 2
- Primary Product/Service 3

## 5. REVENUE MODEL
**Primary:** ${data.revenueModel}
**Secondary:** 
- Direct Sales
- Partnerships
- Subscription Revenue

## 6. MARKETING STRATEGY
- Digital Marketing (SEO, Social Media)
- Content Marketing
- Partnerships & Collaborations
- Customer Referrals
- Paid Advertising

## 7. COMPETITIVE ADVANTAGE
- Unique Value Proposition
- Proprietary Technology
- Strong Customer Relationships
- Experienced Leadership Team

## 8. OPERATIONS
- **Location:** Primary operations in India
- **Technology Stack:** Cloud-based infrastructure
- **Supply Chain:** Optimized partners network

## 9. FINANCIAL PROJECTIONS

### Year 1
- Revenue: ₹50,00,000
- Expenses: ₹40,00,000
- Net Profit: ₹10,00,000

### Year 2
- Revenue: ₹1,50,00,000
- Expenses: ₹1,00,00,000
- Net Profit: ₹50,00,000

### Year 3
- Revenue: ₹5,00,00,000
- Expenses: ₹3,00,00,000
- Net Profit: ₹2,00,00,000

## 10. TEAM
- **Founders:** Industry experts with 10+ years experience
- **Key Hires:** Sales, Marketing, Technology
- **Advisors:** Industry veterans

## 11. MILESTONES & GOALS
${data.goals.filter(g => g.trim()).map((goal, i) => `${i + 1}. ${goal}`).join("\n") || "1. Launch MVP\n2. Acquire first 100 customers\n3. Achieve product-market fit"}

## 12. FUNDING REQUIREMENTS
- **Current Stage:** ${data.funding}
- **Seeking:** ₹${data.teamSize === "1-10" ? "50L" : data.teamSize === "10-50" ? "2Cr" : "10Cr"}
- **Use of Funds:**
  - Product Development: 40%
  - Marketing: 30%
  - Operations: 20%
  - Team Expansion: 10%

## 13. RISK ANALYSIS
| Risk | Probability | Impact | Mitigation |
|------|-------------|--------|------------|
| Market Risk | Medium | High | Market Research |
| Competition | High | Medium | Differentiation |
| Technology Risk | Low | High | R&D Investment |
| Financial Risk | Medium | Medium | Conservative Planning |

## 14. EXIT STRATEGY
- Acquisition by larger player
- IPO in 5-7 years
- Management buyout

---
*Generated by IndiaToolkit.in Business Plan Generator*
      `.trim();

      setGeneratedPlan(plan);
      setIsGenerating(false);
    }, 2000);
  };

  const downloadPlan = () => {
    if (!generatedPlan) return;

    const blob = new Blob([generatedPlan], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${data.companyName.replace(/\s+/g, "-").toLowerCase()}-business-plan.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const copyPlan = () => {
    if (!generatedPlan) return;
    navigator.clipboard.writeText(generatedPlan);
  };

  const resetForm = () => {
    setData({
      companyName: "",
      industry: "Technology",
      mission: "",
      targetMarket: "",
      revenueModel: "",
      teamSize: "1-10",
      funding: "Bootstrapped",
      goals: [""]
    });
    setGeneratedPlan(null);
  };

  return (
    <div className="p-6 md:p-8 space-y-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center h-16 w-16 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl mb-4 shadow-lg">
            <Briefcase className="h-8 w-8 text-white" />
          </div>
          <h2 className="text-2xl font-black text-slate-900 uppercase italic">Business Plan Generator</h2>
          <p className="text-slate-500 font-bold text-sm mt-2">
            Create a professional business plan in minutes
          </p>
        </div>

        {/* Input Form */}
        <div className="bg-white rounded-3xl shadow-xl border border-slate-100 overflow-hidden">
          <div className="p-6 space-y-6">
            {/* Basic Info */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Company Name
                </label>
                <input
                  type="text"
                  value={data.companyName}
                  onChange={(e) => updateField("companyName", e.target.value)}
                  placeholder="Enter your company name"
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Industry
                </label>
                <select
                  value={data.industry}
                  onChange={(e) => updateField("industry", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                >
                  {industries.map((ind) => (
                    <option key={ind} value={ind}>{ind}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Mission */}
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                Mission Statement
              </label>
              <textarea
                value={data.mission}
                onChange={(e) => updateField("mission", e.target.value)}
                placeholder="What is your company's mission?"
                rows={3}
                className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium resize-none"
              />
            </div>

            {/* Target Market */}
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                Target Market
              </label>
              <textarea
                value={data.targetMarket}
                onChange={(e) => updateField("targetMarket", e.target.value)}
                placeholder="Who is your target audience?"
                rows={3}
                className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium resize-none"
              />
            </div>

            {/* Revenue & Team */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Revenue Model
                </label>
                <select
                  value={data.revenueModel}
                  onChange={(e) => updateField("revenueModel", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                >
                  <option value="">Select model...</option>
                  {revenueModels.map((model) => (
                    <option key={model} value={model}>{model}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Team Size
                </label>
                <select
                  value={data.teamSize}
                  onChange={(e) => updateField("teamSize", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                >
                  <option value="1-10">1-10 (Startup)</option>
                  <option value="10-50">10-50 (Growth)</option>
                  <option value="50-200">50-200 (Scale)</option>
                  <option value="200+">200+ (Enterprise)</option>
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Funding Status
                </label>
                <select
                  value={data.funding}
                  onChange={(e) => updateField("funding", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                >
                  <option value="Bootstrapped">Bootstrapped</option>
                  <option value="Angel Invested">Angel Invested</option>
                  <option value="VC Funded">VC Funded</option>
                  <option value="Revenue Positive">Revenue Positive</option>
                </select>
              </div>
            </div>

            {/* Goals */}
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                Key Milestones & Goals
              </label>
              <div className="space-y-3">
                {data.goals.map((goal, index) => (
                  <div key={index} className="flex gap-3">
                    <input
                      type="text"
                      value={goal}
                      onChange={(e) => updateGoal(index, e.target.value)}
                      placeholder={`Goal ${index + 1}`}
                      className="flex-1 p-4 rounded-2xl border-2 border-slate-200 focus:border-blue-500 focus:outline-none font-medium"
                    />
                    {data.goals.length > 1 && (
                      <button
                        onClick={() => removeGoal(index)}
                        className="px-4 py-2 rounded-2xl bg-red-100 text-red-600 font-bold hover:bg-red-200 transition-all"
                      >
                        Remove
                      </button>
                    )}
                  </div>
                ))}
              </div>
              <button
                onClick={addGoal}
                className="mt-3 text-sm text-blue-600 font-bold hover:text-blue-700"
              >
                + Add Another Goal
              </button>
            </div>

            {/* Generate Button */}
            <div className="flex gap-4">
              <button
                onClick={generatePlan}
                disabled={!data.companyName || !data.mission || isGenerating}
                className="flex-1 h-14 bg-gradient-to-r from-blue-500 to-indigo-600 text-white rounded-2xl font-bold flex items-center justify-center gap-2 hover:from-blue-600 hover:to-indigo-700 transition-all shadow-lg shadow-blue-100 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="h-5 w-5" />
                    Generate Business Plan
                  </>
                )}
              </button>

              <button
                onClick={resetForm}
                className="px-6 h-14 rounded-2xl bg-slate-100 text-slate-700 font-bold hover:bg-slate-200 transition-all"
              >
                Reset
              </button>
            </div>
          </div>

          {/* Results */}
          {generatedPlan && (
            <div className="p-6 bg-gradient-to-br from-blue-50 to-indigo-50 border-t border-blue-100">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-blue-800 uppercase text-sm">
                  Generated Business Plan
                </h3>
                <div className="flex gap-2">
                  <button
                    onClick={copyPlan}
                    className="px-4 py-2 bg-white border border-blue-200 text-blue-700 rounded-xl text-sm font-bold hover:bg-blue-50 transition-all"
                  >
                    Copy
                  </button>
                  <button
                    onClick={downloadPlan}
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-bold hover:bg-blue-700 transition-all"
                  >
                    <Download className="h-4 w-4" />
                    Download
                  </button>
                </div>
              </div>

              <div className="bg-white rounded-2xl p-6 border border-blue-100 max-h-96 overflow-y-auto">
                <pre className="text-sm text-slate-700 whitespace-pre-wrap font-mono">
                  {generatedPlan}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Info Cards */}
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 bg-blue-50 rounded-2xl border border-blue-100">
            <Target className="h-8 w-8 text-blue-600 mb-3" />
            <h3 className="font-bold text-blue-800 mb-2">Clear Goals</h3>
            <p className="text-sm text-blue-700">
              Define measurable milestones for your business growth and success.
            </p>
          </div>
          <div className="p-6 bg-indigo-50 rounded-2xl border border-indigo-100">
            <Users className="h-8 w-8 text-indigo-600 mb-3" />
            <h3 className="font-bold text-indigo-800 mb-2">Know Your Market</h3>
            <p className="text-sm text-indigo-700">
              Identify your target audience and understand their needs and pain points.
            </p>
          </div>
          <div className="p-6 bg-purple-50 rounded-2xl border border-purple-100">
            <TrendingUp className="h-8 w-8 text-purple-600 mb-3" />
            <h3 className="font-bold text-purple-800 mb-2">Plan for Growth</h3>
            <p className="text-sm text-purple-700">
              Create realistic financial projections and growth strategies.
            </p>
          </div>
        </div>

        {/* Tips */}
        <div className="mt-6 p-4 bg-amber-50 rounded-xl border border-amber-200">
          <div className="flex items-start gap-3">
            <CheckCircle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-bold text-amber-800 text-sm">Pro Tips for a Winning Business Plan</p>
              <ul className="text-xs text-amber-700 mt-2 space-y-1">
                <li>• Be realistic with financial projections</li>
                <li>• Research your competition thoroughly</li>
                <li>• Define your unique value proposition clearly</li>
                <li>• Include a detailed marketing strategy</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
