"use client";

import { useState } from "react";
import { Calendar, Download, RefreshCw, Sparkles, Target, CheckCircle, BarChart } from "lucide-react";

interface CalendarData {
  topic: string;
  platform: string;
  frequency: string;
  duration: string;
  audience: string;
}

const platforms = ["Instagram", "TikTok", "YouTube", "Twitter/X", "LinkedIn", "Facebook", "Blog", "All Platforms"];
const frequencies = ["Daily", "3x per week", "5x per week", "Weekly", "Bi-weekly", "Monthly"];
const durations = ["1 week", "2 weeks", "1 month", "3 months", "6 months"];
const audiences = ["Gen Z", "Millennials", "Professionals", "Parents", "General"];

export default function ContentCalendarGenerator() {
  const [data, setData] = useState<CalendarData>({
    topic: "",
    platform: "Instagram",
    frequency: "5x per week",
    duration: "1 month",
    audience: "Gen Z"
  });

  const [calendar, setCalendar] = useState<{
    days: { day: string; date: string; content: string; type: string }[];
    themes: string[];
    metrics: { posts: number; engagement: number; growth: number };
  } | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const updateField = (field: keyof CalendarData, value: string) => {
    setData({ ...data, [field]: value });
  };

  const generateCalendar = async () => {
    if (!data.topic.trim()) return;

    setIsGenerating(true);

    setTimeout(() => {
      const daysMap: Record<string, number> = {
        "1 week": 7,
        "2 weeks": 14,
        "1 month": 30,
        "3 months": 90,
        "6 months": 180
      };

      const postsPerWeek: Record<string, number> = {
        "Daily": 7,
        "3x per week": 3,
        "5x per week": 5,
        "Weekly": 1,
        "Bi-weekly": 0.5,
        "Monthly": 0.25
      };

      const totalDays = daysMap[data.duration];
      const postsPerDay = postsPerWeek[data.frequency] / 7;
      const totalPosts = Math.round(totalDays * postsPerDay);

      const contentTypes = [
        "Educational Post", "Behind the Scenes", "User Generated Content", "Product/Service Highlight",
        "Tips & Tricks", "Story/Process", "Q&A Session", "Collaborations", "Contests/Giveaways"
      ];

      const themes = [
        "Monday Motivation", "Tutorial Tuesday", "Wednesday Wisdom", "Throwback Thursday",
        "Feature Friday", "Saturday Stories", "Sunday Setup"
      ];

      const calendarDays = [];
      const today = new Date();

      for (let i = 0; i < totalPosts; i++) {
        const postDate = new Date(today);
        postDate.setDate(today.getDate() + Math.floor(i / postsPerDay));
        
        const contentType = contentTypes[i % contentTypes.length];
        const theme = themes[postDate.getDay()];
        
        calendarDays.push({
          day: postDate.toLocaleDateString("en-US", { weekday: "long" }),
          date: postDate.toLocaleDateString("en-IN", { day: "numeric", month: "short" }),
          content: `${data.topic}: ${contentType} - ${theme}`,
          type: contentType
        });
      }

      setCalendar({
        days: calendarDays,
        themes,
        metrics: {
          posts: totalPosts,
          engagement: Math.round(totalPosts * (data.audience === "Gen Z" ? 5 : data.audience === "Millennials" ? 4 : 3)),
          growth: Math.round(totalPosts * 0.5)
        }
      });

      setIsGenerating(false);
    }, 2000);
  };

  const downloadCalendar = () => {
    if (!calendar) return;

    const text = `
===============================================
  CONTENT CALENDAR - ${data.topic.toUpperCase()}
===============================================

Platform: ${data.platform}
Duration: ${data.duration}
Frequency: ${data.frequency}
Audience: ${data.audience}

Total Planned Posts: ${calendar.metrics.posts}

===============================================
              CALENDAR
===============================================

${calendar.days.map((d, i) => `
Day ${i + 1}: ${d.day}, ${d.date}
Type: ${d.type}
Content: ${d.content}
`).join("")}

===============================================
           WEEKLY THEMES
===============================================

${calendar.themes.map(t => `• ${t}`).join("\n")}

===============================================
        EXPECTED OUTCOMES
===============================================

Est. Posts: ${calendar.metrics.posts}
Est. Engagement Rate: ${calendar.metrics.engagement}%
Est. Follower Growth: +${calendar.metrics.growth}%

===============================================
    Generated by IndiaToolkit.in
===============================================
    `.trim();

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${data.topic.replace(/\s+/g, "-").toLowerCase()}-content-calendar.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const resetForm = () => {
    setData({
      topic: "",
      platform: "Instagram",
      frequency: "5x per week",
      duration: "1 month",
      audience: "Gen Z"
    });
    setCalendar(null);
  };

  return (
    <div className="p-6 md:p-8 space-y-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center h-16 w-16 bg-gradient-to-br from-teal-500 to-cyan-600 rounded-2xl mb-4 shadow-lg">
            <Calendar className="h-8 w-8 text-white" />
          </div>
          <h2 className="text-2xl font-black text-slate-900 uppercase italic">Content Calendar Generator</h2>
          <p className="text-slate-500 font-bold text-sm mt-2">
            Plan your content strategy for weeks and months ahead
          </p>
        </div>

        {/* Input Form */}
        <div className="bg-white rounded-3xl shadow-xl border border-slate-100 overflow-hidden">
          <div className="p-6 space-y-6">
            {/* Topic */}
            <div>
              <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                Content Topic/Niche
              </label>
              <input
                type="text"
                value={data.topic}
                onChange={(e) => updateField("topic", e.target.value)}
                placeholder="e.g., Digital Marketing, Fitness, Cooking"
                className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-teal-500 focus:outline-none font-medium"
              />
            </div>

            {/* Options Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Platform
                </label>
                <select
                  value={data.platform}
                  onChange={(e) => updateField("platform", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-teal-500 focus:outline-none font-medium"
                >
                  {platforms.map((p) => (
                    <option key={p} value={p}>{p}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Posting Frequency
                </label>
                <select
                  value={data.frequency}
                  onChange={(e) => updateField("frequency", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-teal-500 focus:outline-none font-medium"
                >
                  {frequencies.map((f) => (
                    <option key={f} value={f}>{f}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Duration
                </label>
                <select
                  value={data.duration}
                  onChange={(e) => updateField("duration", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-teal-500 focus:outline-none font-medium"
                >
                  {durations.map((d) => (
                    <option key={d} value={d}>{d}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">
                  Target Audience
                </label>
                <select
                  value={data.audience}
                  onChange={(e) => updateField("audience", e.target.value)}
                  className="w-full p-4 rounded-2xl border-2 border-slate-200 focus:border-teal-500 focus:outline-none font-medium"
                >
                  {audiences.map((a) => (
                    <option key={a} value={a}>{a}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Generate Button */}
            <div className="flex gap-4">
              <button
                onClick={generateCalendar}
                disabled={!data.topic.trim() || isGenerating}
                className="flex-1 h-14 bg-gradient-to-r from-teal-500 to-cyan-600 text-white rounded-2xl font-bold flex items-center justify-center gap-2 hover:from-teal-600 hover:to-cyan-700 transition-all shadow-lg shadow-teal-100 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-5 w-5" />
                    Generate Calendar
                  </>
                )}
              </button>

              <button
                onClick={resetForm}
                className="px-6 h-14 rounded-2xl bg-slate-100 text-slate-700 font-bold hover:bg-slate-200 transition-all"
              >
                Reset
              </button>
            </div>
          </div>

          {/* Results */}
          {calendar && (
            <div className="p-6 bg-gradient-to-br from-teal-50 to-cyan-50 border-t border-teal-100">
              {/* Metrics */}
              <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="p-4 bg-white rounded-2xl text-center">
                  <BarChart className="h-6 w-6 text-teal-600 mx-auto mb-2" />
                  <p className="text-2xl font-black text-slate-800">{calendar.metrics.posts}</p>
                  <p className="text-xs text-slate-500 uppercase tracking-widest">Posts</p>
                </div>
                <div className="p-4 bg-white rounded-2xl text-center">
                  <Target className="h-6 w-6 text-teal-600 mx-auto mb-2" />
                  <p className="text-2xl font-black text-slate-800">{calendar.metrics.engagement}%</p>
                  <p className="text-xs text-slate-500 uppercase tracking-widest">Engagement</p>
                </div>
                <div className="p-4 bg-white rounded-2xl text-center">
                  <CheckCircle className="h-6 w-6 text-teal-600 mx-auto mb-2" />
                  <p className="text-2xl font-black text-slate-800">+{calendar.metrics.growth}</p>
                  <p className="text-xs text-slate-500 uppercase tracking-widest">Growth</p>
                </div>
              </div>

              {/* Weekly Themes */}
              <div className="mb-6">
                <span className="text-xs font-bold text-teal-600 uppercase tracking-widest">Weekly Content Themes</span>
                <div className="flex flex-wrap gap-2 mt-3">
                  {calendar.themes.map((theme, index) => (
                    <span key={index} className="px-3 py-1 bg-white border border-teal-200 text-teal-700 rounded-full text-sm font-medium">
                      {theme}
                    </span>
                  ))}
                </div>
              </div>

              {/* Calendar Preview */}
              <div className="mb-4">
                <span className="text-xs font-bold text-teal-600 uppercase tracking-widest">Content Preview</span>
                <div className="mt-3 space-y-2">
                  {calendar.days.slice(0, 7).map((day, index) => (
                    <div key={index} className="flex items-center gap-4 p-3 bg-white rounded-xl">
                      <div className="text-center min-w-[60px]">
                        <p className="text-xs font-bold text-teal-600">{day.day.substring(0, 3)}</p>
                        <p className="text-xs text-slate-400">{day.date}</p>
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-700">{day.content}</p>
                        <p className="text-xs text-teal-600">{day.type}</p>
                      </div>
                    </div>
                  ))}
                  {calendar.days.length > 7 && (
                    <p className="text-center text-xs text-slate-500 py-2">
                      +{calendar.days.length - 7} more posts...
                    </p>
                  )}
                </div>
              </div>

              {/* Download */}
              <button
                onClick={downloadCalendar}
                className="w-full h-12 bg-teal-600 text-white rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-teal-700 transition-all"
              >
                <Download className="h-5 w-5" />
                Download Full Calendar
              </button>
            </div>
          )}
        </div>

        {/* Info Cards */}
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 bg-teal-50 rounded-2xl border border-teal-100">
            <Calendar className="h-8 w-8 text-teal-600 mb-3" />
            <h3 className="font-bold text-teal-800 mb-2">Stay Organized</h3>
            <p className="text-sm text-teal-700">
              Plan your content in advance and maintain consistency.
            </p>
          </div>
          <div className="p-6 bg-cyan-50 rounded-2xl border border-cyan-100">
            <Target className="h-8 w-8 text-cyan-600 mb-3" />
            <h3 className="font-bold text-cyan-800 mb-2">Consistent Posting</h3>
            <p className="text-sm text-cyan-700">
              Regular posting helps algorithms favor your content.
            </p>
          </div>
          <div className="p-6 bg-blue-50 rounded-2xl border border-blue-100">
            <BarChart className="h-8 w-8 text-blue-600 mb-3" />
            <h3 className="font-bold text-blue-800 mb-2">Track Growth</h3>
            <p className="text-sm text-blue-700">
              Measure performance and adjust strategy accordingly.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
